[package]
name = "azhnefatafl"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.13.1"
tch = "0.18.1"

[lib]
name = "main"
path = "rust_part/src/lib.rs"

[[bin]]
name = "azhnefatafl"
path = "rust_part/src/main.rs"
