[package]
name = "hnefatafl"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.13.1"
tch = "0.18.1"

[[bin]]
name = "main"
path = "./rust_part/src/main.rs"

[lib]
name = "hnefatafl"
path = "./rust_part/src/lib.rs"